### PR TITLE
Reject invalid hostnames

### PR DESCRIPTION
**Pull request by calebmckay**
From issue #18

### CODE REVIEW

**Comment by calebmckay** [comment]
This might be another helpful function to put in STcommon.py in case we need to validate the hostname in other files. But for now, I think it's fine in server.py.

**Comment by linted** [comment]
I don't personally see needing to check the hostname in any other files.

Also python is really cool and unlike some langues (c) allows code like `if 1 < x < 4:`. I think that will make the if statement more readable.

Lol don't feel bad that I am asking for so many changes, but there is also a ton of really nice function for strings that let you do basically everything. (i.e `string.rstrip()`)

I love that regex, mostly because I am terrible at regex. However did you consider the time complexity vs  something like `string. isalnum()` on each segment after checking the segment's size? Personally I don't know which would be faster, but it is an interesting query.

**Comment by calebmckay** [comment]
I came up with another (somehow more convoluted) way to do the hostname check, and timed both methods through checking 10000 randomly generated "hostnames". The new method actually cuts the time for the regex almost in half (test code [here](http://pastebin.com/raw/4KbLCURP)), so I guess that's worth doing.

**Comment by linted** [comment]
tbh I don't know what is going on there off the top of my head, but that is a significant speed up, so lets go with it. I assume you tried the simply `if hostname in ".join(string.ascii_letters + string.digits + '-')":` and this was faster right?
###### _I don't like the global, but I can deal with it if we must_

Also there is a bug in your code: 88888888 is a valid hostname, but your code `if labels[-1].isdigit():` will reject it. I suggest changing that line to `if len(labes) > 1 and labels[-1].isdigit():`

**Comment by calebmckay** [comment]
Well, the hardest part to understand is the translate() function. In Python 2.x you could simply add a string of characters to remove, but in Python 3, it only accepts a dictionary argument, hence the translation_table variable. Declaring it outside the function is a weird kinda way to make it static, but without making it static and regenerating the dictionary each iteration, it makes process about 3x slower than the regex method we were using before. It shouldn't be too horrible to deal with, since it is still in the is_valid_hostname namespace.

**Review by linted — APPROVED** [review]

**Pull request merged**
