### PR TITLE
Switch to datetime

### PR DESCRIPTION
**Pull request by calebmckay**
# Switch to datetime - Issue #14 

Added datetime library and updated logging string to use strftime().

### CODE REVIEW

**Comment by linted** [comment]
Good start, however the string being passed into strftime can contain other words.
`date.strftime('month = %b')`

and since date is only used once after being created can we consolidate line 29 & 30?
Also `from datetime import date`

**Comment by calebmckay** [comment]
I was apparently misusing datetime.now(), it's supposed to be datetime.datetime.now(). But then I don't even need it in the first place, since time.strftime() already defaults to the current system time. So I feel silly.

I'm not sure what you mean about the strftime though. Are you suggesting we include variables in the strftime statement? So instead of
`"{0}  {2} Checking in at {1}\n".format(strftime('%b  %d %H:%M:%S'),self.client_address[0], msg[1].strip())`
we use
`strftime('%b  %d %H:%M:%S  {1} Checking in at {0}'.format(self.client_address[0], msg[1].strip()))`
or even worse-looking
`strftime('%b  %d %H:%M:%S  ' + msg[1].strip() + ' Checking in at ' + str(self.client_address[0]))`

**Comment by linted** [comment]
I would personally go with the first option using the format function. The only thing we need to worry about is escaping possible %s in the host name. I am not sure if it will be cleaner to put the call to strftime on a different line then the format because of escaping. 
`"%b".replace('%','%%')`

Also lets stick with datetime because 

> For [time](https://docs.python.org/3/library/datetime.html#datetime.time) objects, the format codes for year, month, and day should not be used, as time objects have no such values. If they’re used anyway, 1900 is substituted for the year, and 1 for the month and day.

 ###### *to be fair I am not sure if that is talking about the time library*

We should be able to do a `from datetime import datetime` since the second datetime is a class

**Comment by linted** [comment]
Don't worry about escaping characters issue #18 should take care of any security implications that may entail.

**Comment by calebmckay** [comment]
I think that quote is referring to the difference between _[datetime.time](https://docs.python.org/3/library/datetime.html#time-objects)_ objects, when what we're using is a _[time](https://docs.python.org/3/library/time.html?highlight=time#module-time)_ object. I tested using `from time import strftime` and `strftime('%d %b %Y')` correctly returns `07 Feb 2017` (or `08 Feb 2017`, if your time zone is UTC like my raspberry pi was).

**Pull request merged**
